// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Repositories;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(ReizenContext))]
    [Migration("20231109170154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Bestemmingen", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<int>("Landid")
                        .HasColumnType("int")
                        .HasColumnName("landid");

                    b.Property<string>("Plaats")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plaats");

                    b.HasKey("Code")
                        .HasName("PK__bestemmi__357D4CF85195F698");

                    b.HasIndex("Landid");

                    b.ToTable("bestemmingen", (string)null);
                });

            modelBuilder.Entity("Model.Boekingen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AantalKinderen")
                        .HasColumnType("int")
                        .HasColumnName("aantalKinderen");

                    b.Property<int?>("AantalVolwassenen")
                        .HasColumnType("int")
                        .HasColumnName("aantalVolwassenen");

                    b.Property<bool>("AnnulatieVerzekering")
                        .HasColumnType("bit")
                        .HasColumnName("annulatieVerzekering");

                    b.Property<DateTime>("GeboektOp")
                        .HasColumnType("date")
                        .HasColumnName("geboektOp");

                    b.Property<int>("Klantid")
                        .HasColumnType("int")
                        .HasColumnName("klantid");

                    b.Property<int>("Reisid")
                        .HasColumnType("int")
                        .HasColumnName("reisid");

                    b.HasKey("Id")
                        .HasName("PK__boekinge__3213E83FFD8466D0");

                    b.HasIndex("Klantid");

                    b.HasIndex("Reisid");

                    b.ToTable("boekingen", (string)null);
                });

            modelBuilder.Entity("Model.Klanten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adres");

                    b.Property<string>("Familienaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("familienaam");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("voornaam");

                    b.Property<int>("Woonplaatsid")
                        .HasColumnType("int")
                        .HasColumnName("woonplaatsid");

                    b.HasKey("Id")
                        .HasName("PK__klanten__3213E83F5F7BC5F9");

                    b.HasIndex("Woonplaatsid");

                    b.ToTable("klanten", (string)null);
                });

            modelBuilder.Entity("Model.Landen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naam");

                    b.Property<int>("Werelddeelid")
                        .HasColumnType("int")
                        .HasColumnName("werelddeelid");

                    b.HasKey("Id")
                        .HasName("PK__landen__3213E83FE37F949B");

                    b.HasIndex("Werelddeelid");

                    b.HasIndex(new[] { "Naam" }, "UQ__landen__72E1CD786B2F2BC9")
                        .IsUnique();

                    b.ToTable("landen", (string)null);
                });

            modelBuilder.Entity("Model.Reizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalDagen")
                        .HasColumnType("int")
                        .HasColumnName("aantalDagen");

                    b.Property<int>("AantalKinderen")
                        .HasColumnType("int")
                        .HasColumnName("aantalKinderen");

                    b.Property<int>("AantalVolwassenen")
                        .HasColumnType("int")
                        .HasColumnName("aantalVolwassenen");

                    b.Property<string>("Bestemmingscode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("bestemmingscode")
                        .IsFixedLength();

                    b.Property<decimal>("PrijsPerPersoon")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prijsPerPersoon");

                    b.Property<DateTime>("Vertrek")
                        .HasColumnType("date")
                        .HasColumnName("vertrek");

                    b.HasKey("Id")
                        .HasName("PK__reizen__3213E83F90472306");

                    b.HasIndex("Bestemmingscode");

                    b.ToTable("reizen", (string)null);
                });

            modelBuilder.Entity("Model.Werelddelen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naam");

                    b.HasKey("Id")
                        .HasName("PK__wereldde__3213E83FC299CEC7");

                    b.HasIndex(new[] { "Naam" }, "UQ__wereldde__72E1CD7807623271")
                        .IsUnique();

                    b.ToTable("werelddelen", (string)null);
                });

            modelBuilder.Entity("Model.Woonplaatsen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naam");

                    b.Property<int>("Postcode")
                        .HasColumnType("int")
                        .HasColumnName("postcode");

                    b.HasKey("Id")
                        .HasName("PK__woonplaa__3213E83F0F699A38");

                    b.ToTable("woonplaatsen", (string)null);
                });

            modelBuilder.Entity("Model.Bestemmingen", b =>
                {
                    b.HasOne("Model.Landen", "Land")
                        .WithMany("Bestemmingens")
                        .HasForeignKey("Landid")
                        .IsRequired()
                        .HasConstraintName("bestemmingen_landen");

                    b.Navigation("Land");
                });

            modelBuilder.Entity("Model.Boekingen", b =>
                {
                    b.HasOne("Model.Klanten", "Klant")
                        .WithMany("Boekingens")
                        .HasForeignKey("Klantid")
                        .IsRequired()
                        .HasConstraintName("boekingen_klanten");

                    b.HasOne("Model.Reizen", "Reis")
                        .WithMany("Boekingens")
                        .HasForeignKey("Reisid")
                        .IsRequired()
                        .HasConstraintName("boekingen_reizen");

                    b.Navigation("Klant");

                    b.Navigation("Reis");
                });

            modelBuilder.Entity("Model.Klanten", b =>
                {
                    b.HasOne("Model.Woonplaatsen", "Woonplaats")
                        .WithMany("Klantens")
                        .HasForeignKey("Woonplaatsid")
                        .IsRequired()
                        .HasConstraintName("klanten_woonplaatsen");

                    b.Navigation("Woonplaats");
                });

            modelBuilder.Entity("Model.Landen", b =>
                {
                    b.HasOne("Model.Werelddelen", "Werelddeel")
                        .WithMany("Landens")
                        .HasForeignKey("Werelddeelid")
                        .IsRequired()
                        .HasConstraintName("landen_werelddelen");

                    b.Navigation("Werelddeel");
                });

            modelBuilder.Entity("Model.Reizen", b =>
                {
                    b.HasOne("Model.Bestemmingen", "BestemmingscodeNavigation")
                        .WithMany("Reizens")
                        .HasForeignKey("Bestemmingscode")
                        .IsRequired()
                        .HasConstraintName("reizen_bestemmingen");

                    b.Navigation("BestemmingscodeNavigation");
                });

            modelBuilder.Entity("Model.Bestemmingen", b =>
                {
                    b.Navigation("Reizens");
                });

            modelBuilder.Entity("Model.Klanten", b =>
                {
                    b.Navigation("Boekingens");
                });

            modelBuilder.Entity("Model.Landen", b =>
                {
                    b.Navigation("Bestemmingens");
                });

            modelBuilder.Entity("Model.Reizen", b =>
                {
                    b.Navigation("Boekingens");
                });

            modelBuilder.Entity("Model.Werelddelen", b =>
                {
                    b.Navigation("Landens");
                });

            modelBuilder.Entity("Model.Woonplaatsen", b =>
                {
                    b.Navigation("Klantens");
                });
#pragma warning restore 612, 618
        }
    }
}
